{% set name = "refinenet" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f85e8f1e7dde6f63345b35cb710ae60fa2f54218218ac3b77ede6368949a9fb1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - acrv_datasets
    - numpy
    - pillow
    - pycocotools
    - python >={{ python_min }}
    - pytorch
    - scipy
    - six
    - torchvision

test:
  imports:
    - refinenet
    - refinenet.datasets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/best-of-acrv/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: RefineNet is a multi-path refinement network for semantic image segmentation
  description: |
    RefineNet is a generic multi-path refinement network for high-resolution
    semantic image segmentation and general dense prediction tasks on images.
    It achieves high-resolution prediction by explicitly exploiting all the
    information available along the down-sampling process and using long-range
    residual connections. It includes a Python API, & scripts for command line
    usage.
  doc_url: https://github.com/best-of-acrv/{{ name }}
  dev_url: https://github.com/best-of-acrv/{{ name }}

extra:
  recipe-maintainers:
    - btalb
